openapi: "3.1.0"

responses:
  400-BadRequest:
    description: "client side error"
    content:
      application/json:
        schema:
          type: object
          properties:
            code: { type: string }
            message: { type: string }

  401-Unauthenticated:
    description: "unauthenticated error"
    content:
      application/json:
        schema:
          type: object
          properties:
            code: { type: string }
            message: { type: string }
        example:
          code: "401"
          message: "権限がありません。再度認証してください。"

  404-NotFound:
    description: "not found error"
    content:
      application/json:
        schema:
          type: object
          properties:
            code: { type: string }
            message: { type: string }
          example:
            code: "404"
            message: "存在しないURLです"
