version: '3.9'

services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: awesome-chat-app
    ports:
      - 5432:5432
    volumes:
      - ./migrations/01_initialize.up.sql:/docker-entrypoint-initdb.d/init.sql
