name: deploy-openapi

on:
  push:
    branches: [ main ]
    paths:
      - 'openapi/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./openapi

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install redocly
        run: npm i -g @redocly/cli@latest
      - name: Build a static file.
        run: redocly build-docs -o ./docs-openapi/index.html openapi.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # 注: top からの相対パスになるので注意（working-directory が無視されてそう）。
          path: ./openapi/docs-openapi/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to gh-pages
        id: deployment
        uses: actions/deploy-pages@v2
